#!/usr/bin/env python3
"""
sync_data.py

Generates JavaScript data files from the JSON source files.
These .js files are loaded via <script> tags in index.html and allow
the tool to work from file:// URLs without needing a server.

Run this any time you edit jargon-data.json or framework-standards-data.json.

Usage:
    python3 sync_data.py

Run from the jargon-decoder folder.
"""

import json
import os
import sys


def generate_js_file(json_path, js_path, var_name):
    """Read a JSON file and write a companion .js file that sets a window global."""
    with open(json_path, 'r', encoding='utf-8') as f:
        data = json.load(f)

    content = f'// Auto-generated by sync_data.py — do not edit directly\n'
    content += f'// Source: {json_path}\n'
    content += f'window.{var_name} = '
    content += json.dumps(data, indent=2, ensure_ascii=False)
    content += ';\n'

    with open(js_path, 'w', encoding='utf-8') as f:
        f.write(content)

    return len(data.get('entries', []))


def main():
    # Verify working directory
    if not os.path.exists('jargon-data.json'):
        print("ERROR: jargon-data.json not found.")
        print("Run this script from the jargon-decoder folder.")
        sys.exit(1)
    if not os.path.exists('framework-standards-data.json'):
        print("ERROR: framework-standards-data.json not found.")
        print("Run this script from the jargon-decoder folder.")
        sys.exit(1)

    print("Generating data files...\n")

    # Generate jargon-data.js
    count1 = generate_js_file('jargon-data.json', 'jargon-data.js', 'JARGON_DATA')
    size1 = os.path.getsize('jargon-data.js')
    print(f"  jargon-data.js")
    print(f"    Entries: {count1}")
    print(f"    Size: {size1:,} bytes ({size1 / 1024:.0f} KB)\n")

    # Generate framework-standards-data.js
    count2 = generate_js_file('framework-standards-data.json', 'framework-standards-data.js', 'FRAMEWORKS_DATA')
    size2 = os.path.getsize('framework-standards-data.js')
    print(f"  framework-standards-data.js")
    print(f"    Entries: {count2}")
    print(f"    Size: {size2:,} bytes ({size2 / 1024:.0f} KB)\n")

    print(f"Total entries: {count1 + count2}")
    print(f"Total data size: {(size1 + size2) / 1024:.0f} KB\n")
    print("Done. Open index.html in any browser.")


if __name__ == '__main__':
    main()
